services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
    ports:
      - "11434:11434"
    restart: unless-stopped

volumes:
  ollama: {}
